#! /bin/sh

set -e

# Test search server
NODE_ENV=test npm start &
PID1=$!
sleep 5
mocha --compilers coffee:coffee-script/register
kill $PID1

# Test static site
wintersmith preview &
PID2=$!
sleep 5
grunt linkChecker:dev
kill $PID2
